### ISSUE TITLE
Better resolution management

### ISSUE THREAD

**Issue by SamirHafez** [mitchellh/nixos-config#19]
https://github.com/mitchellh/nixos-config/blob/639860c58debcf3c5b4727a8e487c1921c64d1b3/machines/vm-shared.nix#L59-L64

I think `services.xserver.resolutions = [{ x = 2880; y = 1800; }]` would be a simpler way to achieve this, instead of using `xrandr` directly

**Comment by mitchellh** [comment]
Perhaps, I'm happy with how it is for now... and eventually VMware should support automatic resolution setting and we can just delete all this.
