### ISSUE TITLE
nix-shell FHS interop throws cryptic error

### ISSUE THREAD

**Issue by allancalix** [mitchellh/nixos-config#21]
Interesting idea, thanks for sharing the configurations. Wondering if anyone else has experienced issues with running nix-shell for tools that expect FHS systems. Using nix-shell without build an FHS environment seems to work fine.

## Host System
OSX 12.2.1 - Apple M1 Pro
   
## Shell Configuration
```nix
# shell.nix
{ pkgs ? import <nixpkgs> {} }:
(pkgs.buildFHSUserEnv {
   name = "dev";
   targetPkgs = pkgs : [];
}).env
```
## Error thrown                                           
```bash
** (process:25978): ERROR **: 18:24:13.384: main: execvp(*argv, argv): No such file or directory      │
fish: Job 1, 'nix-shell' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by mitchellh** [comment]
Going to close this as stale...

I have no idea and it seems no one else does either atm.
