### ISSUE TITLE
error while configuring nixos

### ISSUE THREAD

**Issue by Rudra1106** [mitchellh/nixos-config#40]
i am working on mac m1 , and trying to setup nixos in vmware fusion , But
when trying to execute this step --> make vm/bootstrap0 , i'm getting this error :

building the configuration in /mnt/etc/nixos/configuration.nix...
error:
       … while calling the 'head' builtin
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: nixVersions.unstable has been removed. For bleeding edge (Nix master, roughly weekly updated) use nixVersions.git, otherwise use nixVersions.latest.
make: *** [vm/bootstrap0] Error 1

error image :-

<img width="1161" alt="Screenshot 2024-06-22 at 11 14 26 PM" src="https://github.com/mitchellh/nixos-config/assets/115483864/0e7ad41e-d49e-4245-9648-a848f35c3cbc">

**Comment by Rudra1106** [comment]
> I have seen the same issue. And confirmed the PR resolved it in my env vm-aarch64-utm.

Sorry but can u please elaborate a little on how to solve this issue if possible.

**Comment by yysushi** [comment]
in the above, I added one PR link describing how to update Makefile.

![Screenshot 2024-06-24 at 11 00 44 AM](https://github.com/mitchellh/nixos-config/assets/33568261/95a38d15-43c9-4190-923f-d88d96c4e063)

**Comment by Rudra1106** [comment]
> in the above, I added one PR link describing how to update Makefile.
> 
> ![Screenshot 2024-06-24 at 11 00 44 AM](https://private-user-images.githubusercontent.com/33568261/342444738-95a38d15-43c9-4190-923f-d88d96c4e063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTI1ODEsIm5iZiI6MTcxOTI1MjI4MSwicGF0aCI6Ii8zMzU2ODI2MS8zNDI0NDQ3MzgtOTVhMzhkMTUtNDNjOS00MTkwLTkyM2YtZDg4ZDk2YzRlMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE4MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3Nzg2MDE0YTZjMzY2NjAyMjRiMWFlODJlYmMyOGFjZWYwNGJkYWM3NDIyYjgwM2JiYmIxZjhhNTdhOWE3OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l4xUz_s37NrTsw81EOQ5LkjVu_awyfqoFxXmYTQFozY)



> in the above, I added one PR link describing how to update Makefile.
> 
> ![Screenshot 2024-06-24 at 11 00 44 AM](https://private-user-images.githubusercontent.com/33568261/342444738-95a38d15-43c9-4190-923f-d88d96c4e063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTI1ODEsIm5iZiI6MTcxOTI1MjI4MSwicGF0aCI6Ii8zMzU2ODI2MS8zNDI0NDQ3MzgtOTVhMzhkMTUtNDNjOS00MTkwLTkyM2YtZDg4ZDk2YzRlMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE4MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3Nzg2MDE0YTZjMzY2NjAyMjRiMWFlODJlYmMyOGFjZWYwNGJkYWM3NDIyYjgwM2JiYmIxZjhhNTdhOWE3OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l4xUz_s37NrTsw81EOQ5LkjVu_awyfqoFxXmYTQFozY)

it worked !! thnk u veryyy much for your help .

**Comment by Rudra1106** [comment]
in my m1 mac , while using this script --> make vm/bootstrap , i'm facing this issue 
does anyone know about this problem ?

<img width="1680" alt="Screenshot 2024-06-25 at 2 27 16 PM" src="https://github.com/mitchellh/nixos-config/assets/115483864/d212b7ed-1719-430d-99e8-bf98405638e8">
