### ISSUE TITLE
running it on Windows

### ISSUE THREAD

**Issue by kohlerm** [mitchellh/nixos-config#8]
Hi Mitchell, 
I can confirm that everything  runs fine on Windows with VMware (pro) 16.x :-)
I used WSL2 for running the Makefile because, apart from make a few other tools are needed. 
Checking out the repo from WS2 directly avoids some problems with end of line feeds. 
I had some trouble at times with kernel going into emergency mode and complaining about being unable to mount host. 
I believe this was caused by me not following closely how you configured the VM (3d Acceleration, sound off sharing enabled).
The Readme still says SATA where as you otherwise mentioned that with the Makefile as is, it only works with SCSI. 
 
Otherwise thanks a lot for open sourcing this!
I am a huge fan of running reproducible Dev environments on Linux(VMs mostly) and I am also  running nix on  Windows WSL2 since a while.   A few years ago (ok almost 8 years) I was creating and maintaining dev environments for a couple of hundred developers, which worked quite well. this was (well is, because it seems people are still using it) based on Chef scripts (yes 😢 ) and later Docker.

**Comment by kohlerm** [comment]
oh and adding some hint about how to change your password might be helpful for people  ;-)
` mkpasswd -m sha-512 `

**Comment by mitchellh** [comment]
Thanks! I'm going to close this issue, I think having this issue exist for people to search is good enoguh, but thanks for letting me know!
